from __future__ import annotations

import json
import os
import subprocess
import tempfile
import time
from pathlib import Path

import typer

from treeforge_ab.install.full_ab import build_full_ab_plan
from treeforge_ab.install.input import resolve_input
from treeforge_ab.providers.fastboot_runtime import (
    stage_fastboot_f2fs_runtime,
)
from treeforge_ab.providers.android_tools import (
    AndroidHostTools,
    treeforge_adb_executable,
    treeforge_fastboot_executable,
)
from treeforge_ab.repartition.device import (
    TangorproRepartitionDeviceController,
)
from treeforge_ab.repartition.execution import (
    TangorproRepartitionExecutor,
)
from treeforge_ab.runtime_source import (
    resolve_aosp_runtime_source,
)


CANONICAL_SUPER_BYTES = 20_000_538_624

PHYSICAL_PARTITIONS = (
    "boot",
    "init_boot",
    "dtbo",
    "vendor_kernel_boot",
    "pvmfw",
    "vendor_boot",
    "vbmeta",
    "vbmeta_system",
    "vbmeta_vendor",
)

DYNAMIC_PARTITIONS = (
    "system",
    "system_dlkm",
    "system_ext",
    "product",
    "vendor",
    "vendor_dlkm",
)


class ConversionError(RuntimeError):
    pass


class ConversionCancelled(RuntimeError):
    pass


def repository_root() -> Path:
    return (
        Path(__file__)
        .resolve()
        .parents[2]
    )


def _run_capture(
    command: list[str],
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        command,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        check=False,
    )


def _single_fastboot_serial(
    fastboot: Path,
) -> str:
    completed = _run_capture(
        [
            str(fastboot),
            "devices",
        ]
    )

    if completed.returncode != 0:
        raise ConversionError(
            "fastboot devices failed"
        )

    serials = []

    for raw in completed.stdout.splitlines():
        fields = raw.split()

        if fields:
            serials.append(
                fields[0]
            )

    serials = list(
        dict.fromkeys(serials)
    )

    if len(serials) != 1:
        raise ConversionError(
            "Exactly one fastboot device is required; "
            f"found {len(serials)}."
        )

    return serials[0]


def _wait_fastboot(
    fastboot: Path,
    *,
    timeout: int = 90,
) -> str:
    deadline = (
        time.monotonic()
        + timeout
    )

    while time.monotonic() < deadline:
        try:
            return _single_fastboot_serial(
                fastboot
            )
        except ConversionError:
            time.sleep(1)

    raise ConversionError(
        "Timed out waiting for fastboot."
    )


def _ensure_bootloader_interactive(
    controller: TangorproRepartitionDeviceController,
) -> bool:
    source_transport = None

    if controller._fastboot_present():
        userspace = (
            controller._fastboot_userspace()
        )

        if userspace is None:
            raise ConversionError(
                "Unable to classify fastboot transport."
            )

        if userspace:
            source_transport = "fastbootd"

    elif controller._adb_present():
        source_transport = "Android / ADB"

    else:
        raise ConversionError(
            "No supported device transport detected."
        )

    if source_transport is None:
        return False

    typer.echo(
        f"Current transport: {source_transport}"
    )
    typer.echo(
        "Bootloader fastboot is required."
    )

    if not typer.confirm(
        "Reboot to bootloader now?",
        default=True,
    ):
        raise ConversionCancelled(
            "Bootloader transition declined."
        )

    controller.ensure_bootloader()

    return True


def _image_map(build):
    result = {}

    for image in build.images:
        if image.partition not in result:
            result[image.partition] = image

    required = (
        PHYSICAL_PARTITIONS
        + DYNAMIC_PARTITIONS
    )

    missing = [
        name
        for name in required
        if name not in result
    ]

    if missing:
        raise ConversionError(
            "Validated input is missing conversion "
            "images: "
            + ", ".join(missing)
        )

    return result


def _render_full_ab_manifest(
    build,
) -> str:
    images = _image_map(build)

    lines = [
        "version 1",
        "# Generated by treeforge-ab.",
        "# Layout: treeforge-full-ab-v1.",
        "# Physical boot chain mirrored A + B.",
        "# Complete dynamic logical slot A + B.",
        "# Shared super realized exactly once.",
        "# Conversion wipe: userdata + metadata.",
        "# No final Android reboot.",
    ]

    for partition in PHYSICAL_PARTITIONS:
        image = images[partition]

        options = []

        if image.apply_vbmeta:
            options.append(
                "--apply-vbmeta"
            )

        lines.append(
            " ".join(
                (
                    "flash",
                    *options,
                    partition,
                    f"{partition}.img",
                )
            )
        )

        lines.append(
            " ".join(
                (
                    "flash",
                    "--slot-other",
                    *options,
                    partition,
                    f"{partition}.img",
                )
            )
        )

    lines.append(
        "reboot fastboot"
    )

    #
    # Exactly one LP metadata realization.
    #
    lines.append(
        "update-super"
    )

    for partition in DYNAMIC_PARTITIONS:
        lines.append(
            f"flash {partition} "
            f"{partition}.img"
        )

        lines.append(
            f"flash --slot-other "
            f"{partition} "
            f"{partition}.img"
        )

    #
    # KEEP THE WIPE.
    #
    lines.append(
        "if-wipe erase userdata"
    )
    lines.append(
        "if-wipe erase metadata"
    )

    return (
        "\n".join(lines)
        + "\n"
    )


def _link(
    target: Path,
    source: Path,
) -> None:
    source = (
        source
        .expanduser()
        .resolve()
    )

    if not source.is_file():
        raise ConversionError(
            "Required runtime artifact is missing: "
            f"{source}"
        )

    target.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    if (
        target.exists()
        or target.is_symlink()
    ):
        target.unlink()

    target.symlink_to(
        source
    )


def _runtime_product(
    *,
    root: Path,
    resolved,
    generated_super: Path,
    manifest: str,
) -> None:
    images = _image_map(
        resolved.build
    )

    for partition in (
        PHYSICAL_PARTITIONS
        + DYNAMIC_PARTITIONS
    ):
        _link(
            root / f"{partition}.img",
            images[partition].path,
        )

    _link(
        root / "super_empty.img",
        generated_super,
    )

    android_info = (
        resolved.build.android_info_path
    )

    if (
        android_info is not None
        and Path(android_info).is_file()
    ):
        _link(
            root / "android-info.txt",
            Path(android_info),
        )

    else:
        (
            root / "android-info.txt"
        ).write_text(
            "board=tangorpro\n",
            encoding="utf-8",
        )

    (
        root / "fastboot-info.txt"
    ).write_text(
        manifest,
        encoding="utf-8",
    )


def _provider_environment(
    *,
    fastboot: Path,
) -> dict[str, str]:
    tools = AndroidHostTools()

    make_f2fs = Path(
        tools.make_f2fs
    ).resolve()

    if not make_f2fs.is_file():
        raise ConversionError(
            "Exact android-image-tools make_f2fs "
            "provider is unavailable."
        )

    environment = os.environ.copy()

    #
    # No distro/AOSP/PATH fallback.
    #
    environment["PATH"] = (
        os.pathsep.join(
            (
                str(fastboot.parent),
                str(make_f2fs.parent),
            )
        )
    )

    return environment


def _execute_full_ab_flash(
    *,
    resolved,
    generated_super: Path,
    current_slot: str,
    manifest: str,
) -> tuple[str, str]:
    provider_fastboot = Path(
        treeforge_fastboot_executable()
    ).resolve()

    #
    # Critical:
    # fastboot's F2FS generator executes make_f2fs from
    # fastboot's own executable directory.
    #
    fastboot = (
        stage_fastboot_f2fs_runtime(
            repository_root=(
                repository_root()
            ),
            fastboot=provider_fastboot,
        )
    )

    serial = _single_fastboot_serial(
        fastboot
    )

    environment = (
        _provider_environment(
            fastboot=fastboot
        )
    )

    with tempfile.TemporaryDirectory(
        prefix="treeforge-ab-convert-"
    ) as temporary:
        runtime = Path(
            temporary
        )

        _runtime_product(
            root=runtime,
            resolved=resolved,
            generated_super=generated_super,
            manifest=manifest,
        )

        environment[
            "ANDROID_PRODUCT_OUT"
        ] = str(runtime)

        command = [
            str(fastboot),
            "-s",
            serial,

            #
            # Initial conversion wipe remains mandatory.
            #
            "-w",

            "--slot",
            current_slot,

            #
            # Never boot Android automatically.
            #
            "--skip-reboot",

            "flashall",
        ]

        typer.echo()
        typer.echo(
            "=== FULL A/B FLASH ==="
        )
        typer.echo(
            "Physical boot chain: A + B"
        )
        typer.echo(
            "Dynamic partitions: COMPLETE A + B"
        )
        typer.echo(
            "update-super: EXACTLY ONCE"
        )
        typer.echo(
            "userdata wipe: YES"
        )
        typer.echo(
            "metadata wipe: YES"
        )
        typer.echo(
            "Automatic Android reboot: NO"
        )
        typer.echo(
            "Post-install set-active: NO"
        )
        typer.echo()

        completed = subprocess.run(
            command,
            env=environment,
            check=False,
        )

        if completed.returncode != 0:
            raise ConversionError(
                "Full-A/B fastboot transaction "
                "failed with exit status "
                f"{completed.returncode}."
            )

    serial = _wait_fastboot(
        fastboot
    )

    userspace = _run_capture(
        [
            str(fastboot),
            "-s",
            serial,
            "getvar",
            "is-userspace",
        ]
    )

    combined = (
        userspace.stdout
        + "\n"
        + userspace.stderr
    ).lower()

    if (
        "is-userspace: yes"
        in combined
    ):
        typer.echo(
            "Returning from fastbootd to "
            "bootloader fastboot..."
        )

        completed = subprocess.run(
            [
                str(fastboot),
                "-s",
                serial,
                "reboot",
                "bootloader",
            ],
            check=False,
        )

        if completed.returncode != 0:
            raise ConversionError(
                "Unable to return to bootloader "
                "for final filesystem recreation."
            )

        serial = _wait_fastboot(
            fastboot
        )

    #
    # Explicitly recreate both F2FS filesystems.
    #
    # Do this even though -w remains on flashall:
    # Pixel bootloader reports these partitions as raw,
    # so TreeForge supplies the validated F2FS override.
    #
    for partition in (
        "userdata",
        "metadata",
    ):
        typer.echo(
            f"Formatting {partition} as f2fs..."
        )

        completed = subprocess.run(
            [
                str(fastboot),
                "-s",
                serial,
                "format:f2fs",
                partition,
            ],
            env=environment,
            check=False,
        )

        if completed.returncode != 0:
            raise ConversionError(
                f"Formatting {partition} as f2fs "
                "failed."
            )

    return (
        serial,
        "bootloader-fastboot",
    )


def _write_json(
    path: Path,
    payload,
) -> None:
    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    path.write_text(
        json.dumps(
            payload,
            indent=2,
            sort_keys=True,
        )
        + "\n",
        encoding="utf-8",
    )


def run_conversion(
    *,
    input_path: Path,
    super_size: str = "20GB",
    aosp_root: Path | None = None,
    output_root: Path | None = None,
) -> None:
    repo = repository_root()

    if output_root is None:
        output_root = (
            repo
            / "output"
            / "conversion"
        )

    output_root = (
        output_root
        .expanduser()
        .resolve()
    )

    output_root.mkdir(
        parents=True,
        exist_ok=True,
    )

    #
    # 1. Validate source BEFORE destructive admission.
    #
    resolved = resolve_input(
        input_path
        .expanduser()
        .resolve()
    )

    #
    # 2. Exact device admission.
    #
    controller = (
        TangorproRepartitionDeviceController()
    )

    transport_changed = (
        _ensure_bootloader_interactive(
            controller
        )
    )

    device = (
        controller.probe_read_only()
    )

    geometry = (
        controller.validate_inspect(
            device=device
        )
    )

    migration = (
        controller.build_forward_plan(
            device=device,
            requested_super_size=super_size,
        )
    )

    if (
        migration.realized_super_size_bytes
        != CANONICAL_SUPER_BYTES
    ):
        raise ConversionError(
            "v0.1 conversion requires canonical "
            "20GB super geometry: "
            f"{CANONICAL_SUPER_BYTES:,} bytes."
        )

    #
    # 3. Complete full-A/B capacity/LP projection.
    #
    full_ab_root = (
        output_root / "full-ab"
    )

    full_ab = build_full_ab_plan(
        repository_root=repo,
        build=resolved.build,
        super_size_bytes=(
            migration.realized_super_size_bytes
        ),
        output_root=full_ab_root,
    )

    generated_super = (
        full_ab_root
        / "super_empty-treeforge-full-ab-v1.img"
    )

    if not generated_super.is_file():
        raise ConversionError(
            "Full-A/B planner did not produce "
            f"{generated_super}"
        )

    #
    # 4. Resolve temporary runtime.
    #
    runtime_source = (
        resolve_aosp_runtime_source(
            aosp_root
        )
    )

    fastboot = Path(
        treeforge_fastboot_executable()
    ).resolve()

    executor = (
        TangorproRepartitionExecutor(
            repository_root=repo,
            fastboot=str(fastboot),
            runtime_source=runtime_source,
        )
    )

    formatter = (
        executor.preflight_formatters()
    )

    #
    # 5. Every physical boot-chain image MUST really be A/B.
    #
    for partition in PHYSICAL_PARTITIONS:
        applicable = (
            controller._getvar(
                f"has-slot:{partition}"
            )
        )

        if (
            applicable
            .strip()
            .lower()
            != "yes"
        ):
            raise ConversionError(
                "Required physical partition is not "
                "A/B slotted: "
                f"{partition} -> {applicable!r}"
            )

    manifest = (
        _render_full_ab_manifest(
            resolved.build
        )
    )

    manifest_path = (
        output_root
        / "fastboot-info-treeforge-full-ab-v1.txt"
    )

    manifest_path.write_text(
        manifest,
        encoding="utf-8",
    )

    _write_json(
        output_root
        / "conversion-preflight.json",
        {
            "schema_version": 1,
            "input": {
                "kind":
                    resolved.kind,
                "product":
                    resolved.product,
                "baseline":
                    resolved.baseline,
                "bootloader":
                    resolved.bootloader,
            },
            "device":
                device.to_dict(),
            "starting_geometry":
                geometry,
            "migration":
                migration.to_dict(),
            "full_ab":
                full_ab.to_dict(),
            "runtime": {
                "origin":
                    runtime_source.origin,
                "product_out":
                    str(
                        runtime_source
                        .product_out
                    ),
                "boot_image":
                    str(
                        runtime_source
                        .boot_image
                    ),
                "fstab":
                    str(
                        runtime_source
                        .fstab_path
                    ),
            },
            "wipe_policy": {
                "userdata":
                    "MANDATORY",
                "metadata":
                    "MANDATORY",
                "fastboot_wipe_flag":
                    True,
            },
            "automatic_android_reboot":
                False,
            "automatic_set_active":
                False,
        },
    )

    typer.echo()
    typer.echo(
        "============================================"
    )
    typer.echo(
        "TREEFORGE A/B CONVERSION — FINAL PREFLIGHT"
    )
    typer.echo(
        "============================================"
    )
    typer.echo()
    typer.echo(
        f"Input:             {resolved.kind}"
    )
    typer.echo(
        f"Baseline:          {resolved.baseline}"
    )
    typer.echo(
        f"Device:            {device.product}"
    )
    typer.echo(
        f"Current slot:      {device.current_slot}"
    )
    typer.echo(
        f"Starting layout:   {geometry}"
    )
    typer.echo(
        f"Current super:     "
        f"{device.super_size_bytes:,} bytes"
    )
    typer.echo(
        f"Target super:      "
        f"{migration.realized_super_size_bytes:,} bytes"
    )
    typer.echo(
        f"Super delta:       "
        f"{migration.super_delta_bytes:+,} bytes"
    )
    typer.echo()
    typer.echo(
        "Full-A/B LP plan:          VERIFIED"
    )
    typer.echo(
        "Physical boot chain A+B:   YES"
    )
    typer.echo(
        "Complete logical slot A:   YES"
    )
    typer.echo(
        "Complete logical slot B:   YES"
    )
    typer.echo(
        "Logical partition count:   12"
    )
    typer.echo(
        "update-super count:         1"
    )
    typer.echo()
    typer.echo(
        "USERDATA WIPE:              YES — MANDATORY"
    )
    typer.echo(
        "METADATA WIPE:              YES — MANDATORY"
    )
    typer.echo(
        "userdata recreation:        YES"
    )
    typer.echo(
        "metadata recreation:        YES"
    )
    typer.echo()
    typer.echo(
        "Automatic Android reboot:   NO"
    )
    typer.echo(
        "Post-install set-active:    NO"
    )
    typer.echo(
        f"AOSP runtime: {runtime_source.product_out}"
    )
    typer.echo(
        "Transport changed: "
        + (
            "YES"
            if transport_changed
            else "NO"
        )
    )
    typer.echo()
    typer.echo(
        "THIS WILL PERMANENTLY ERASE ALL USER DATA."
    )
    typer.echo(
        "Apps, accounts, settings, downloads, "
        "and all /data contents WILL BE LOST."
    )
    typer.echo()

    if not typer.confirm(
        "Continue with destructive full-A/B conversion?",
        default=False,
    ):
        typer.echo(
            "Conversion cancelled. "
            "No destructive conversion was started."
        )
        return

    #
    # 6. Physical 10GB/stock -> canonical 20GB.
    #    This wipes/recreates userdata AND metadata.
    #
    if migration.super_delta_bytes > 0:
        typer.echo()
        typer.echo(
            "=== PHYSICAL REPARTITION ==="
        )

        run_root = executor.execute(
            plan=migration,
            formatter=formatter,
        )

        typer.echo(
            "GPT migration: PASS"
        )
        typer.echo(
            "userdata recreation: PASS"
        )
        typer.echo(
            "metadata recreation: PASS"
        )
        typer.echo(
            f"Recovery artifacts: {run_root}"
        )

    elif migration.super_delta_bytes == 0:
        typer.echo()
        typer.echo(
            "Physical geometry already canonical; "
            "GPT rewrite skipped."
        )

    else:
        raise ConversionError(
            "Forward conversion unexpectedly "
            "requested a super shrink."
        )

    #
    # 7. From this point onward a simple physical shrink
    #    must NOT be attempted: the LP metadata is about
    #    to become a 20GB full-A/B layout.
    #
    if executor.state_path.is_file():
        state = executor._load_state()

        state[
            "full_ab_flash_started"
        ] = True

        state[
            "automatic_physical_undo"
        ] = False

        state[
            "automatic_physical_undo_reason"
        ] = (
            "full-A/B realization has started; "
            "super LP contents may now target 20GB"
        )

        executor._write_state(
            state
        )

    #
    # 8. Full physical + logical A/B realization.
    #
    serial, final_mode = (
        _execute_full_ab_flash(
            resolved=resolved,
            generated_super=generated_super,
            current_slot=device.current_slot,
            manifest=manifest,
        )
    )

    if executor.state_path.is_file():
        state = executor._load_state()

        state[
            "logical_layout_realized"
        ] = True

        state[
            "logical_layout"
        ] = "treeforge-full-ab-v1"

        state[
            "conversion_status"
        ] = "complete"

        state[
            "status"
        ] = "applied"

        state[
            "filesystems_recreated"
        ] = True

        state[
            "userdata_wiped"
        ] = True

        state[
            "metadata_wiped"
        ] = True

        executor._write_state(
            state
        )

    _write_json(
        output_root
        / "conversion-result.json",
        {
            "status":
                "complete",
            "serial":
                serial,
            "final_fastboot_mode":
                final_mode,
            "active_slot_changed":
                False,
            "android_rebooted":
                False,
            "userdata_wiped":
                True,
            "metadata_wiped":
                True,
            "layout":
                "treeforge-full-ab-v1",
        },
    )

    typer.echo()
    typer.echo(
        "============================================"
    )
    typer.echo(
        "TREEFORGE FULL-A/B CONVERSION COMPLETE"
    )
    typer.echo(
        "============================================"
    )
    typer.echo(
        f"Device left in: {final_mode}"
    )
    typer.echo(
        "Physical boot chain A+B: COMPLETE"
    )
    typer.echo(
        "Logical slot A: COMPLETE"
    )
    typer.echo(
        "Logical slot B: COMPLETE"
    )
    typer.echo(
        "userdata wipe: COMPLETE"
    )
    typer.echo(
        "metadata wipe: COMPLETE"
    )
    typer.echo(
        "Automatic Android reboot: NO"
    )
    typer.echo(
        "Post-install set-active: NO"
    )


def run_undo(
    *,
    aosp_root: Path | None = None,
) -> None:
    repo = repository_root()

    controller = (
        TangorproRepartitionDeviceController()
    )

    _ensure_bootloader_interactive(
        controller
    )

    device = (
        controller.probe_read_only()
    )

    geometry = (
        controller.validate_inspect(
            device=device
        )
    )

    fastboot = Path(
        treeforge_fastboot_executable()
    ).resolve()

    runtime_source = (
        resolve_aosp_runtime_source(
            aosp_root
        )
    )

    executor = (
        TangorproRepartitionExecutor(
            repository_root=repo,
            fastboot=str(fastboot),
            runtime_source=runtime_source,
        )
    )

    #
    # Adopt the old development 10GB rollback state once.
    #
    if (
        not executor.state_path.is_file()
        and geometry == "treeforge-10gb"
    ):
        executor._write_state(
            executor._import_legacy_10gb_state()
        )

    #
    # This refuses automatically after full-A/B LP
    # realization, which is intentional and safe.
    #
    plan = (
        executor
        .build_undo_plan_from_state()
    )

    formatter = (
        executor.preflight_formatters()
    )

    target_userdata = (
        plan.new_userdata_size_sectors
        * plan.sector_size_bytes
    )

    typer.echo()
    typer.echo(
        "=== TREEFORGE A/B PHYSICAL UNDO ==="
    )
    typer.echo(
        f"Current super:   "
        f"{device.super_size_bytes:,} bytes"
    )
    typer.echo(
        f"Target super:    "
        f"{plan.realized_super_size_bytes:,} bytes"
    )
    typer.echo(
        f"Target userdata: "
        f"{target_userdata:,} bytes"
    )
    typer.echo(
        "userdata wipe/recreate: YES"
    )
    typer.echo(
        "metadata wipe/recreate: YES"
    )
    typer.echo(
        "Automatic Android reboot: NO"
    )
    typer.echo()

    if not typer.confirm(
        "Continue with destructive rollback?",
        default=False,
    ):
        typer.echo(
            "Undo cancelled."
        )
        return

    run_root = executor.execute(
        plan=plan,
        formatter=formatter,
    )

    typer.echo()
    typer.echo(
        "Undo complete."
    )
    typer.echo(
        f"Recovery artifacts: {run_root}"
    )
    typer.echo(
        "Device left in bootloader fastboot."
    )


def _adb_boot_completed(
    *,
    adb: Path,
    serial: str,
) -> bool:
    completed = _run_capture(
        [
            str(adb),
            "-s",
            serial,
            "shell",
            "getprop",
            "sys.boot_completed",
        ]
    )

    return (
        completed.returncode == 0
        and completed.stdout.strip()
        == "1"
    )


def _wait_android_boot(
    *,
    adb: Path,
    serial: str,
    timeout: int = 120,
) -> bool:
    deadline = (
        time.monotonic()
        + timeout
    )

    while time.monotonic() < deadline:
        if _adb_boot_completed(
            adb=adb,
            serial=serial,
        ):
            return True

        time.sleep(2)

    return False


def run_slot_validation() -> None:
    controller = (
        TangorproRepartitionDeviceController()
    )

    _ensure_bootloader_interactive(
        controller
    )

    device = (
        controller.probe_read_only()
    )

    controller.validate_inspect(
        device=device
    )

    fastboot = Path(
        treeforge_fastboot_executable()
    ).resolve()

    adb = Path(
        treeforge_adb_executable()
    ).resolve()

    serial = _single_fastboot_serial(
        fastboot
    )

    original_slot = device.current_slot

    results = {}

    for slot in (
        "a",
        "b",
    ):
        typer.echo()
        typer.echo(
            f"=== VALIDATE SLOT {slot.upper()} ==="
        )

        set_active = subprocess.run(
            [
                str(fastboot),
                "-s",
                serial,
                "set_active",
                slot,
            ],
            check=False,
        )

        if set_active.returncode != 0:
            raise ConversionError(
                f"Unable to activate slot {slot}."
            )

        reboot = subprocess.run(
            [
                str(fastboot),
                "-s",
                serial,
                "reboot",
            ],
            check=False,
        )

        if reboot.returncode != 0:
            raise ConversionError(
                f"Unable to boot slot {slot}."
            )

        adb_evidence = (
            _wait_android_boot(
                adb=adb,
                serial=serial,
            )
        )

        typer.echo(
            "ADB boot-completed evidence: "
            + (
                "YES"
                if adb_evidence
                else "NO"
            )
        )

        success = typer.confirm(
            "Did Android finish booting "
            f"successfully on slot "
            f"{slot.upper()}?",
            default=adb_evidence,
        )

        results[slot] = success

        if adb_evidence:
            completed = subprocess.run(
                [
                    str(adb),
                    "-s",
                    serial,
                    "reboot",
                    "bootloader",
                ],
                check=False,
            )

            if completed.returncode != 0:
                raise ConversionError(
                    "Unable to return to bootloader "
                    f"from slot {slot}."
                )

            serial = _wait_fastboot(
                fastboot
            )

        else:
            typer.echo(
                "Return the tablet to bootloader "
                "fastboot manually."
            )

            typer.prompt(
                "Press Enter once bootloader fastboot "
                "is visible",
                default="",
                show_default=False,
            )

            serial = _wait_fastboot(
                fastboot
            )

    typer.echo()
    typer.echo(
        "=== SLOT VALIDATION RESULT ==="
    )
    typer.echo(
        "Slot A: "
        + (
            "PASS"
            if results["a"]
            else "FAIL"
        )
    )
    typer.echo(
        "Slot B: "
        + (
            "PASS"
            if results["b"]
            else "FAIL"
        )
    )

    if typer.confirm(
        "Restore original active slot "
        f"{original_slot.upper()}?",
        default=True,
    ):
        completed = subprocess.run(
            [
                str(fastboot),
                "-s",
                serial,
                "set_active",
                original_slot,
            ],
            check=False,
        )

        if completed.returncode != 0:
            raise ConversionError(
                "Unable to restore original "
                "active slot."
            )

        typer.echo(
            "Original active slot restored."
        )

    typer.echo(
        "Automatic Android reboot: NO"
    )
    typer.echo(
        "Device left in bootloader fastboot."
    )
